class CreateFootballGames < ActiveRecord::Migration[5.0]
  def change
    create_table :football_games do |t|

    	t.string :game_key, null: false
    	t.datetime :date_time
    	t.integer :season_type, null: false
    	t.integer :season, null: false
    	t.integer :week
    	t.string :stadium
    	t.string :playing_surface
    	t.integer :temperature
    	t.integer :humidity
    	t.integer :wind_speed
    	t.string :away_team, null: false
    	t.string :home_team, null: false
    	t.integer :away_score
    	t.integer :home_score
    	t.integer :total_score
    	t.decimal :over_under
    	t.decimal :point_spread
    	t.integer :away_score_quarter_1
    	t.integer :away_score_quarter_2
    	t.integer :away_score_quarter_3
    	t.integer :away_score_quarter_4
    	t.integer :away_score_overtime
    	t.integer :home_score_quarter_1
    	t.integer :home_score_quarter_2
    	t.integer :home_score_quarter_3
    	t.integer :home_score_quarter_4
    	t.integer :home_score_overtime
    	t.string :away_time_of_possession
    	t.string :home_time_of_possession
    	t.integer :away_first_downs
    	t.integer :home_first_downs
    	t.integer :away_first_downs_by_rushing
    	t.integer :home_first_downs_by_rushing
    	t.integer :away_first_downs_by_passing
    	t.integer :home_first_downs_by_passing
    	t.integer :away_first_downs_by_penalty
    	t.integer :home_first_downs_by_penalty
    	t.integer :away_offensive_plays
    	t.integer :home_offensive_plays
    	t.integer :away_offensive_yards
    	t.integer :home_offensive_yards
    	t.decimal :away_offensive_yards_per_play
    	t.decimal :home_offensive_yards_per_play
    	t.integer :away_touchdowns
    	t.integer :home_touchdowns
    	t.integer :away_rushing_attempts
    	t.integer :home_rushing_attempts
    	t.integer :away_rushing_yards
    	t.integer :home_rushing_yards
    	t.decimal :away_rushing_yards_per_attempt
    	t.decimal :home_rushing_yards_per_attempt
    	t.integer :away_rushing_touchdowns
    	t.integer :away_passing_touchdowns
    	t.integer :away_passing_attempts
    	t.integer :away_passing_completions
    	t.integer :away_passing_yards
    	t.integer :away_passing_interceptions
    	t.decimal :away_passing_yards_per_attempt
    	t.decimal :away_passing_yards_per_completion
    	t.integer :home_rushing_touchdowns
    	t.integer :home_passing_touchdowns
    	t.integer :home_passing_attempts
    	t.integer :home_passing_completions
    	t.integer :home_passing_yards
    	t.integer :home_passing_interceptions
    	t.decimal :home_passing_yards_per_attempt
    	t.decimal :home_passing_yards_per_completion
    	t.decimal :away_completion_percentage
    	t.decimal :away_passer_rating
    	t.integer :away_third_down_attempt
    	t.integer :away_third_down_conversions
    	t.decimal :away_third_down_percentage
    	t.integer :away_fourth_down_attempts
    	t.integer :away_fourth_down_conversions
    	t.decimal :away_fourth_down_percentage
    	t.decimal :home_completion_percentage
    	t.decimal :home_passer_rating
    	t.integer :home_third_down_attempt
    	t.integer :home_third_down_conversions
    	t.decimal :home_third_down_percentage
    	t.integer :home_fourth_down_attempts
    	t.integer :home_fourth_down_conversions
    	t.decimal :home_fourth_down_percentage
    	t.integer :away_red_zone_attempts
    	t.integer :away_red_zone_convesions
    	t.integer :away_goal_to_go_attempts
    	t.integer :away_goal_to_go_converstions
    	t.integer :away_return_yards
    	t.integer :away_penalties
    	t.integer :away_penalty_yards
    	t.integer :home_red_zone_attempts
    	t.integer :home_red_zone_convesions
    	t.integer :home_goal_to_go_attempts
    	t.integer :home_goal_to_go_converstions
    	t.integer :home_return_yards
    	t.integer :home_penalties
    	t.integer :home_penalty_yards
    	t.integer :away_fumbles
    	t.integer :away_fumbles_lost
    	t.integer :away_times_sacked
    	t.integer :away_times_sacked_yards
    	t.integer :away_safeties
    	t.integer :away_punts
    	t.integer :away_punts_yards
    	t.decimal :away_punt_average
    	t.integer :away_give_aways
    	t.integer :away_take_aways
    	t.integer :home_fumbles
    	t.integer :home_fumbles_lost
    	t.integer :home_times_sacked
    	t.integer :home_times_sacked_yards
    	t.integer :home_safeties
    	t.integer :home_punts
    	t.integer :home_punts_yards
    	t.decimal :home_punt_average
    	t.integer :home_give_aways
    	t.integer :home_take_aways
    	t.integer :away_turn_over_differential
    	t.integer :away_kickoffs
    	t.integer :away_kickoffs_in_end_zone
    	t.integer :away_kickoffs_touch_backs
    	t.integer :away_punts_had_blocked
    	t.decimal :away_punts_net_average
    	t.integer :away_extra_point_kicking_attempts
    	t.integer :home_turn_over_differential
    	t.integer :home_kickoffs
    	t.integer :home_kickoffs_in_end_zone
    	t.integer :home_kickoffs_touch_backs
    	t.integer :home_punts_had_blocked
    	t.decimal :home_punts_net_average
    	t.integer :home_extra_point_kicking_attempts
    	t.integer :away_extra_point_kicking_conversions
    	t.integer :away_extra_points_had_blocked
    	t.integer :away_extra_points_passing_attempts
    	t.integer :away_extra_points_passing_conversions
    	t.integer :away_extra_point_rushing_attempts
    	t.integer :away_extra_point_rushing_conversions
    	t.integer :away_field_goal_attempts
    	t.integer :home_extra_point_kicking_conversions
    	t.integer :home_extra_points_had_blocked
    	t.integer :home_extra_points_passing_attempts
    	t.integer :home_extra_points_passing_conversions
    	t.integer :home_extra_point_rushing_attempts
    	t.integer :home_extra_point_rushing_conversions
    	t.integer :home_field_goal_attempts
    	t.integer :away_field_goals_made
    	t.integer :away_field_goals_had_blocked
    	t.integer :away_punt_return
    	t.integer :away_punt_return_yards
    	t.integer :away_kick_returns
    	t.integer :away_kick_return_yards
    	t.integer :away_interception_returns
    	t.integer :away_interception_return_yards
        t.integer :home_field_goals_made
    	t.integer :home_field_goals_had_blocked
    	t.integer :home_punt_return
    	t.integer :home_punt_return_yards
    	t.integer :home_kick_returns
    	t.integer :home_kick_return_yards
    	t.integer :home_interception_returns
    	t.integer :home_interception_return_yards
    	t.integer :away_solo_tackles
    	t.integer :away_assisted_tackles
    	t.integer :away_quarter_back_hits
    	t.integer :away_tackles_for_loss
    	t.integer :away_sack
    	t.integer :away_sacked_yards
    	t.integer :away_passes_defended
    	t.integer :away_fumbles_forced
    	t.integer :away_fumbles_recovered
    	t.integer :away_fumble_return_yards
    	t.integer :away_fumble_return_touchtowns
    	t.integer :away_interceptions_return_touchdowns
    	t.integer :away_blocked_kicks
    	t.integer :away_punt_return_touchdowns
    	t.integer :away_punt_return_long
    	t.integer :away_kick_return_touchdowns
    	t.integer :away_kick_return_long
    	t.integer :away_blocked_kick_return_yards
    	t.integer :away_blocked_kick_return_touchdowns
    	t.integer :away_field_goal_return_yards
    	t.integer :away_field_goal_return_touchdowns
    	t.integer :away_punt_net_yards
        t.integer :home_solo_tackles
    	t.integer :home_assisted_tackles
    	t.integer :home_quarter_back_hits
    	t.integer :home_tackles_for_loss
    	t.integer :home_sack
    	t.integer :home_sacked_yards
    	t.integer :home_passes_defended
    	t.integer :home_fumbles_forced
    	t.integer :home_fumbles_recovered
    	t.integer :home_fumble_return_yards
    	t.integer :home_fumble_return_touchtowns
    	t.integer :home_interceptions_return_touchdowns
    	t.integer :home_blocked_kicks
    	t.integer :home_punt_return_touchdowns
    	t.integer :home_punt_return_long
    	t.integer :home_kick_return_touchdowns
    	t.integer :home_kick_return_long
    	t.integer :home_blocked_kick_return_yards
    	t.integer :home_blocked_kick_return_touchdowns
    	t.integer :home_field_goal_return_yards
    	t.integer :home_field_goal_return_touchdowns
    	t.integer :home_punt_net_yards
    	t.boolean :is_game_over
    	t.references :football_stadium, index: true, foreign_key: true
        t.integer :away_two_point_conversion_returns
        t.integer :home_two_point_conversion_returns


        t.decimal :point_spread
        t.decimal :over_under
        t.integer :away_team_money_line
        t.integer :home_team_money_line
        t.integer :forecast_temp_low
        t.integer :forecast_temp_high
        t.integer :forecast_description
        t.integer :forecast_wind_chill
        t.integer :forecast_wind_speed






      t.timestamps null: false
    end
  end
end
